import Document, { Html, Head, Main, NextScript } from 'next/document'

class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head> 
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
	      </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument;